### ISSUE TITLE
Run nakilon/git-to-gcs@1 Failing

### ISSUE THREAD

**Issue by husain3012** [Nakilon/git-to-gcs#1]
I have done the steps as shown in the readme, but my flow keeps on failing.
It says something like:

```/main.rb:5:in `fetch': key not found: "images" (KeyError)
	from /main.rb:5:in `block in <main>'
	from /main.rb:3:in `each'
	from /main.rb:3:in `<main>'```
Here is an image for the same:
![image](https://user-images.githubusercontent.com/49821470/142731781-f89188d0-d78c-4d5a-8f7a-5b9466ffacc8.png)
I am pretty sure that I have entered the right secrets, but don't know why it's happening.

**Comment by Nakilon** [comment]
I suppose your repo has a folder `images` in its root and you don't own such bucket (buckets are globally unique in GCS and someone must have already claimed it). The root of the repo has to have only the folders with the names equal to the bucket names. For example:
![image](https://user-images.githubusercontent.com/2870363/142738312-702de17c-9a4b-45e7-88ce-3cf65f67d509.png)
```
irb> Dir[?*]
=> ["README.md", "www.nakilon.pro"]
```
This skips the `README.md` on the `File.directory? bucket` condition and then syncs the remaining folder to a GSC bucket with the same name I own. Maybe your repo has all sorts of folders that represent your website structure -- you have to move them all in a one top level folder with the name equal to the bucket name.

**Comment by husain3012** [comment]
Oh, okay, got it. Thank You!
